export const caseLog = [
  {
    case_id: 123,
    case_name: '登录成功123',
    logs: ['=== start case: 1 ===', '=== 用例ID: 123  用例名称: 登录成功123==='],
    fail: true,
    data_dict: {
      1: {
        data_id: 1,
        data_name: '123-第一个',
        fail: true,
        logs: {
          request_before: {
            description: '参数前置准备',

            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',

            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',

            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',

            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',

            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',

            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            fail: true,
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            fail: true,
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
      2: {
        data_id: 2,
        data_name: '123-第一个',
        logs: {
          request_before: {
            description: '参数前置准备',
            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',
            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',
            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',
            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',
            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',
            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
      3: {
        data_id: 2,
        data_name: '123-第一个',
        logs: {
          request_before: {
            description: '参数前置准备',
            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',
            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',
            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',
            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',
            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',
            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
      4: {
        data_id: 2,
        data_name: '123-第一个',
        logs: {
          request_before: {
            description: '参数前置准备',
            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',
            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',
            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',
            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',
            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',
            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
      5: {
        data_id: 2,
        data_name: '123-第一个',
        logs: {
          request_before: {
            description: '参数前置准备',
            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',
            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',
            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',
            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',
            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',
            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
    },
  },
  {
    case_id: 123,
    fail: true,
    case_name: '登录成功123',
    logs: ['=== start case: 1 ===', '=== 用例ID: 123  用例名称: 登录成功123==='],
    data_dict: {
      1: {
        data_id: 1,
        data_name: '123-第一个',
        logs: {
          request_before: {
            description: '参数前置准备',
            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',
            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',
            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',
            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',
            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',
            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
    },
  },
  {
    case_id: 123,
    case_name: '登录成功123',
    logs: ['=== start case: 1 ===', '=== 用例ID: 123  用例名称: 登录成功123==='],
    fail: true,
    data_dict: {
      1: {
        data_id: 1,
        data_name: '123-第一个',
        fail: true,
        logs: {
          request_before: {
            description: '参数前置准备',

            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',

            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',

            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',

            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',

            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',

            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            fail: true,
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            fail: true,
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
      2: {
        data_id: 2,
        data_name: '123-第一个',
        fail: true,
        logs: {
          request_before: {
            description: '参数前置准备',
            logs: ['=== 参数前置准备:1-123-第一个 ==='],
          },
          url: {
            description: '请求地址',
            logs: ['=== 数据驱动:1 ===', 'http://106.75.174.40:5000/api/login'],
          },
          method: {
            description: '请求方式',
            logs: ['POST'],
          },
          request_headers: {
            description: '请求头',
            type: null,
            logs: [
              {
                token: '{"a": "123"}',
                token123: '123-第一个',
              },
            ],
          },
          request_body: {
            description: '请求体',
            logs: [
              {
                a: 1,
                b: '测试用例B1',
                password: '123456',
                username: 'admin',
              },
            ],
          },
          http_code: {
            description: 'HTTP响应码',
            logs: [200],
          },
          response_headers: {
            description: '响应头',
            logs: [
              {
                'Content-Type': 'application/json',
                'Content-Length': '440',
                log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
              },
            ],
          },
          response_body: {
            description: '响应体',
            type: null,
            logs: [
              {
                code: 200,
                data: {
                  code: '00001',
                  create_time: '2022-06-27 14:02:18',
                  create_timestamp: 1656309738,
                  creator: 'shell',
                  creator_id: 0,
                  id: 1,
                  is_deleted: 0,
                  mail: null,
                  modifier: null,
                  modifier_id: null,
                  nickname: null,
                  phone: null,
                  remark: 'manage shell',
                  status: 1,
                  token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
                  update_time: '2022-06-27 14:02:18',
                  update_timestamp: null,
                  username: 'admin',
                },
                message: '登录成功',
              },
            ],
          },
          request_after: {
            description: '参数后置准备',
            logs: ['=== 参数后置准备:1-123-第一个 ==='],
          },
          response_assert: {
            description: '响应断言',
            logs: [
              '=== 公式取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [==] 200:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [>] 100:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 200 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'code': 200} ===",
              "function: <class 'int'>",
              "200:<class 'int'> [<] 300:int",
              '=== Response 断言通过 ===',
              '=== 取值结果: 登录成功 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'message': '登录成功'} ===",
              "function: <class 'str'>",
              "登录成功:<class 'str'> [==] 登录成功:str",
              '=== Response 断言通过 ===',
              '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
              '=== 断言:1-123-第一个 ===',
              "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
              "function: <class 'str'>",
              "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
              '=== Response 断言失败 ===',
            ],
          },
          field_assert: {
            description: '字段断言',
            logs: ["=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个"],
          },
        },
        logs_summary: [
          '=== 前置准备 ===',
          '=== 参数前置准备:1-123-第一个 ===',
          '=== 请求地址接口 ===',
          '=== 数据驱动:1 ===',
          '=== 请求地址接口 ===',
          'http://106.75.174.40:5000/api/login',
          '=== 请求方式 ===',
          'POST',
          '=== 请求头 ===',
          {
            token: '{"a": "123"}',
            token123: '123-第一个',
          },
          '=== 请求体 ===',
          {
            a: 1,
            b: '测试用例B1',
            password: '123456',
            username: 'admin',
          },
          '=== HTTP响应码 ===',
          200,
          '=== 响应头 ===',
          {
            'Content-Type': 'application/json',
            'Content-Length': '440',
            log_uuid: '1661505631_27c9cZq7HQJEreyGcSgEq4',
          },
          '=== 响应体 ===',
          {
            code: 200,
            data: {
              code: '00001',
              create_time: '2022-06-27 14:02:18',
              create_timestamp: 1656309738,
              creator: 'shell',
              creator_id: 0,
              id: 1,
              is_deleted: 0,
              mail: null,
              modifier: null,
              modifier_id: null,
              nickname: null,
              phone: null,
              remark: 'manage shell',
              status: 1,
              token: '54f99448YYx2520YYx11edYYxaafeYYx5254002f96eb',
              update_time: '2022-06-27 14:02:18',
              update_timestamp: null,
              username: 'admin',
            },
            message: '登录成功',
          },
          '=== 后置准备 ===',
          '=== 参数后置准备:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          '=== 公式取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [==] 200:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [>] 100:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 200 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'code': 200} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'int'>",
          '=== 响应断言汇总 ===',
          "200:<class 'int'> [<] 300:int",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 登录成功 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'message': '登录成功'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "登录成功:<class 'str'> [==] 登录成功:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言通过 ===',
          '=== 响应断言汇总 ===',
          '=== 取值结果: 1661505631_27c9cZq7HQJEreyGcSgEq4 ===',
          '=== 响应断言汇总 ===',
          '=== 断言:1-123-第一个 ===',
          '=== 响应断言汇总 ===',
          "=== 键值:{'log_uuid': '1661505631_27c9cZq7HQJEreyGcSgEq4'} ===",
          '=== 响应断言汇总 ===',
          "function: <class 'str'>",
          '=== 响应断言汇总 ===',
          "1661505631_27c9cZq7HQJEreyGcSgEq4:<class 'str'> [==] 1661338972_HZwpNW7x6jCRfhfwqmmyPh:str",
          '=== 响应断言汇总 ===',
          '=== Response 断言失败 ===',
          '=== 字段断言汇总 ===',
          "=== case_resp_ass_info ===\n[{'field_ass': '1'}]\n1-123-第一个",
        ],
      },
    },
  },
]
